services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - USUARIO=${USUARIO}
      - PASSWORD=${PASSWORD}

