@startuml PauletAssistant

package domain {
  class Calificacion
  class CalificacionesPeriodo
  class Curso
  class HorarioDiario
  class HorarioSemanal
  class MenuItem
  class MenuOption
}

package application {
  interface CacheInterface
  interface WebScraperInterface
  interface ChatbotInterface
  class ChatbotService
  class MenuService
  class ConversationStateService
  abstract class ConsultaUseCase
  class ConsultarNotasUseCase
  class ConsultarHorariosUseCase
}

package infrastructure {
  class BaseCacheImpl
  class RedisCacheImpl
  class BaseWebScraperImpl
  class CalificacionPlaywrightScraperImpl
  class HorariosWebScraperImpl
  class ChatbotPresenter
  class CalificacionPresenter
  class HorariosPresenter
  class PeriodosCalificacionPresenter
  class RedisConfig
  class RedisClient
  class AuthLoader
  class MenuLoader
  class ChatbotRoutes
  class CacheRoutes
  class MonitoringRoutes
  class SystemMonitor
}

ConsultaUseCase <|-- ConsultarNotasUseCase
ConsultaUseCase <|-- ConsultarHorariosUseCase
BaseCacheImpl <|-- RedisCacheImpl
BaseWebScraperImpl <|-- CalificacionPlaywrightScraperImpl
BaseWebScraperImpl <|-- HorariosWebScraperImpl
CacheInterface <|.. BaseCacheImpl
WebScraperInterface <|.. BaseWebScraperImpl
ChatbotInterface <|.. ChatbotService
ChatbotService --> MenuService
ChatbotService --> ConversationStateService
ChatbotService --> ConsultarNotasUseCase
ChatbotService --> ConsultarHorariosUseCase
ChatbotService --> ChatbotPresenter
MenuService --> ConversationStateService
ConsultarNotasUseCase --> CalificacionPlaywrightScraperImpl
ConsultarNotasUseCase --> RedisCacheImpl
ConsultarHorariosUseCase --> HorariosWebScraperImpl
ConsultarHorariosUseCase --> RedisCacheImpl
RedisCacheImpl --> RedisClient
CalificacionPlaywrightScraperImpl --> AuthLoader
HorariosWebScraperImpl --> AuthLoader
ChatbotPresenter --> ChatbotService
CalificacionPresenter --> ConsultarNotasUseCase
HorariosPresenter --> ConsultarHorariosUseCase
PeriodosCalificacionPresenter --> ConsultarNotasUseCase
CalificacionesPeriodo --> Calificacion
HorarioDiario --> Curso
HorarioSemanal --> HorarioDiario
MenuItem --> MenuOption

@enduml